// import type { NextPage } from "next";
import Head from "next/head";

const Home = () => {
  return (
    <div className="w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline bg-red-500">Hello world!</h1>
    </div>
  );
};

export default Home;
